--zad17
SELECT PSEUDO "POLUJE W POLU", PRZYDZIAL_MYSZY "PRZYDZIAL MYSZY", NAZWA "BANDA"
FROM KOCURY K JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
WHERE (TEREN = 'POLE' OR TEREN = 'CALOSC')
    AND PRZYDZIAL_MYSZY > 50;
    
--zad18
SELECT K1.IMIE, K1.W_STADKU_OD "POLUJE OD"
FROM KOCURY K1 JOIN KOCURY K2 ON K1.PSEUDO = K2.PSEUDO 
WHERE K2.IMIE = 'JACEK' AND K1.W_STADKU_OD < K2.W_STADKU_OD;